### ISSUE TITLE
Nonexistent flag '-o'

### ISSUE THREAD

**Issue by julian-hoch** [litencatt/notion-cli#246]
The help text has this sample command:

  Query a db with a specific database_id and output format
    $ notion-cli db query -o csv DATABASE_ID

But when I try this, I get:
    Error: Nonexistent flag: -o
    See more help with --help

This is:
» notion-cli --version
@litencatt/notion-cli/0.14.1 wsl-x64 node-v20.10.0

**Comment by julian-hoch** [comment]
Thanks, that helps! But I guess the -r example is also incorrect, this does not seem to take an example (I guess that would be -a).
On a related note, the system always prompts for a filter when querying, is there a non-interactive mode so it can be more easily be triggered from a script?

**Comment by litencatt** [comment]
@julian-hoch 

> Thanks, that helps! But I guess the -r example is also incorrect, this does not seem to take an example (I guess that would be -a).

Thanks for your report. I fix it.

> On a related note, the system always prompts for a filter when querying, is there a non-interactive mode so it can be more easily be triggered from a script?

Thanks. I improved abount non-interactive execution for query a database.
https://github.com/litencatt/notion-cli/pull/259
